include:
  - opensearch.yaml
services:
  alfresco-ai-framework:
    image: alfresco-ai-framework:latest
    environment:
      - spring.ai.vectorstore.opensearch.uris=${OPENSEARCH_URIS}
      - spring.ai.ollama.base-url=${OLLAMA_BASE_URL}
    depends_on:
      opensearch:
        condition: service_healthy
    ports:
      - "9999:9999"