include:
  - elasticsearch.yaml
services:
  alfresco-ai-framework:
    image: alfresco-ai-framework
    build: ../
    environment:
      - SPRING_ELASTICSEARCH_URIS=${ELASTICSEARCH_URIS}
      - SPRING_AI_OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "9999:9999"