services:
  alfresco-ai-framework:
    image: alfresco-ai-framework:latest
    environment:
      - spring.elasticsearch.uris=http://elasticsearch:9200
      - spring.ai.ollama.base-url=http://host.docker.internal:11434
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8080:8080"
  elasticsearch:
    image: elasticsearch:8.12.2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - network.host=0.0.0.0
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3