services:
  ollama:
    image: ollama/ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    pull_policy: always
    tty: true
    volumes:
      - ollama-models:/root/.ollama
      - ollama-data:/root/.cache/ollama
volumes:
  ollama-models:
  ollama-data: