spring:
  application:
    name: ai-framework
  http:
    client:
      connect-timeout: 60s
      read-timeout: 60s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    chat:
      client:
        observations:
          include-input: true
      observations:
        include-completion: true
        include-prompt: true
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: mistral
          temperature: 0.0
      embedding:
        options:
          model: nomic-embed-text
    vectorstore:
      observations:
        include-query-response: true
      opensearch:
        uris: http://opensearch:9200
        index-name: alfresco-ai-document-index
        username: admin
        password: Alfresco.org.2024

server:
  port: 9999

cors:
  filter:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"