spring:
  application:
    name: ai-framework
  http:
    client:
      connect-timeout: 60s
      read-timeout: 60s
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  elasticsearch:
    uris: http://localhost:9200

  ai:
    model:
      chat: openai
    openai:
      base-url: http://localhost:12434/engines
      api-key: nokeyrequired
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: ai/qwen2.5
          temperature: 0.0
      embedding:
        options:
          model: ai/mxbai-embed-large
    vectorstore:
      elasticsearch:
        initialize-schema: true
        index-name: alfresco-ai-document-index
        dimensions: 768

server:
  port: 9999

cors:
  filter:
    disabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"